name: Lianne

channels:
  - bioconda
  - conda-forge
  - default
  - pkgs/r

dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _r-mutex
  - alsa-lib
  - bcl2fastq
  - bedtools
  - binutils_impl_linux-64
  - binutils_linux-64
  - boost_lib
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - curl
  - fastqc
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - fribidi
  - gcc_impl_linux-64
  - gcc_linux-64
  - gettext
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - giflib
  - graphite2
  - gsl
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - htslib
  - icu
  - jbig
  - jpeg
  - jvarkit-bam2wig
  - kernel-headers_linux-64
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - lz4-c
  - make
  - mosdepth
  - ncurses
  - openjdk
  - openssl
  - pango
  - pcre
  - pcre2
  - perl
  - perl-app-cpanminus
  - pixman
  - pthread-stubs
  - r-assertthat
  - r-backports
  - r-base
  - r-cairo
  - r-cli
  - r-colorspace
  - r-crayon
  - r-desc
  - r-digest
  - r-dplyr
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-farver
  - r-generics
  - r-ggplot2
  - r-glue
  - r-gtable
  - r-isoband
  - r-labeling
  - r-lattice
  - r-lifecycle
  - r-magrittr
  - r-mass
  - r-matrix
  - r-mclust
  - r-mgcv
  - r-munsell
  - r-nlme
  - r-pillar
  - r-pkgconfig
  - r-pkgload
  - r-plyr
  - r-praise
  - r-purrr
  - r-r6
  - r-rcolorbrewer
  - r-rcpp
  - r-reshape2
  - r-rlang
  - r-rprojroot
  - r-rstudioapi
  - r-scales
  - r-stringi
  - r-stringr
  - r-testthat
  - r-tibble
  - r-tidyselect
  - r-utf8
  - r-vctrs
  - r-viridislite
  - r-withr
  - readline
  - sed
  - sysroot_linux-64
  - tk
  - tktable
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-libxt
  - xorg-libxtst
  - xorg-recordproto
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd
