name: Lianne

channels:
  - bioconda
  - conda-forge
  - default
  - pkgs/r

dependencies:
  - bedtools
  - fastqc
  - htslib
  - mosdepth
  - openjdk
  - openssl
  - pango
  - pcre
  - pcre2
  - perl
  - perl-app-cpanminus
  - r-assertthat
  - r-backports
  - r-base
  - r-cairo
  - r-cli
  - r-colorspace
  - r-crayon
  - r-desc
  - r-digest
  - r-dplyr
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-farver
  - r-generics
  - r-ggplot2
  - r-glue
  - r-gtable
  - r-isoband
  - r-labeling
  - r-lattice
  - r-lifecycle
  - r-magrittr
  - r-mass
  - r-matrix
  - r-mclust
  - r-mgcv
  - r-munsell
  - r-nlme
  - r-pillar
  - r-pkgconfig
  - r-pkgload
  - r-plyr
  - r-praise
  - r-purrr
  - r-r6
  - r-rcolorbrewer
  - r-rcpp
  - r-reshape2
  - r-rlang
  - r-rprojroot
  - r-rstudioapi
  - r-scales
  - r-stringi
  - r-stringr
  - r-testthat
  - r-tibble
  - r-tidyselect
  - r-utf8
  - r-vctrs
  - r-viridislite
  - r-withr
  - readline
  - sed